spring:
  thymeleaf:
    cache: false
server:
  ip: 192.168.126.129
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://192.168.126.129:2181
  consumer:
    check: false
fdfs:
  tracker-list:
    - 192.168.126.129:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false